[package]
name = "meme"
version = "1.0.0"
authors = []

[addresses]
addr = '85da3573f71a7059b4c5eed699e3caf6b2c4baa9933549b264c671def594a2f4'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dev-dependencies]
